export const cards = [
  {
    id: 1,
    title: "English Writing Skills: From Basics to Brilliance",
    description: "Whether you're writing emails, essays, or reports, this course covers everything you need to improve your writing. Start from the basics and work your way to creating compelling, well-structured content.",
    imageUrl: "/images/1.jpg",
    duration: "3 months",
    fee: 1, 
    hasFreeTrial: true,
    videos: [
      { title: "Introduction", url: "https://videos.pexels.com/video-files/29725551/12779576_2560_1440_30fps.mp4" },
      { title: "Grammer", url: "/videos/js-functions.mp4" },
    ],
    pdfUrl: "/pdfs/yash.pdf",
    faculty:"Yashdeep Sir"
  },
  {
    id: 2,
    title: "Advanced English Communication",
    description: "Take your English skills to the next level with our advanced communication course. Perfect for those looking to enhance their speaking, listening, and writing abilities for high-level conversations and professional environments.",
    imageUrl: "/images/2.jpg",
    duration: "24 months",
    fee: 2,
    hasFreeTrial: true, 
  },
  {
    id: 3,
    title: "Speak Like a Native",
    description: "Ever wanted to sound like a native English speaker? In this course, we’ll teach you natural phrases, slang, and pronunciation techniques to help you sound like you’ve been speaking English your whole life.",
    imageUrl: "/images/3.jpg",
    duration: "1 month",
    fee: 1,
    hasFreeTrial: true, 
  },
  {
    id: 4,
    title: "English for Business Excellence",
    description: "Enhance your English communication skills for the workplace. Whether you’re writing emails, participating in meetings, or presenting, this course covers everything you need to succeed in the business world.",
    imageUrl: "/images/4.jpg",
    duration: "11 months",
    fee: 1,
    hasFreeTrial: true, 
  },
  {
    id: 5,
    title: "Fluent English for Career Growth",
    description: "Learn how to use English effectively to advance in your career. This course helps you refine your language skills in areas like interviews, negotiations, and workplace communication to give you a competitive edge.",
    imageUrl: "/images/5.jpg",
    duration: "4 months",
    fee: 2,
    hasFreeTrial: true, 
  },
  {
    id: 6,
    title: "Mastering English Fluency",
    description: "Unlock the power of fluent English in both professional and casual settings. This course will help you build confidence in speaking and listening, enabling you to communicate effortlessly in any situation.",
    imageUrl: "/images/6.jpg",
    duration: "9 months",
    fee: 1,
    hasFreeTrial: true, 
  },
];
